---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    update_cache: yes
    state: present

- name: Stop and disable
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Add dnsmasq config
  copy:
    dest: /etc/private.conf
    content: |
      domain-needed
      bind-interfaces
      bogus-priv
      local=/openstack-aio.net/
      interface=bond0
      listen-address=10.200.0.100,172.20.200.11
      interface=br-pxe
      addn-hosts=/etc/banner_add_hosts
      strict-order
      expand-hosts
      domain=openstack-aio.net
      no-resolv
      server={{host_nameservers}}
      #log-queries

- name: Add dnsmasq hosts
  blockinfile:
    path: /etc/banner_add_hosts
    create: yes
    block: |
      10.200.0.100 public public.openstack-aio.net
      172.29.236.100 private private.openstack-aio.net

- name: Remove resolv.conf soft link
  file:
    path: /etc/resolv.conf
    state: absent

- name: Add nameservers to resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    create: yes
    block: |
      nameserver {{host_nameservers}}
      nameserver {{ ansible_default_ipv4.address }}

- name: Add dnsmasq unit
  copy:
    dest: /etc/systemd/system/dnsmasq-private.service
    content: |
      [Unit]
      Description=Private DNS server
      Requires=network.target
      After=network.target

      [Service]
      Type=forking
      PIDFile=/run/dnsmasq/dnsmasq-private.pid

      # Test the config file and refuse starting if it is not valid.
      ExecStartPre=/usr/sbin/dnsmasq --test -C /etc/private.conf
      # We run dnsmasq via the /etc/init.d/dnsmasq script which acts as a
      # wrapper picking up extra configuration files and then execs dnsmasq
      # itself, when called with the "systemd-exec" function.
      ExecStart=/usr/sbin/dnsmasq -C /etc/private.conf -x /run/dnsmasq/dnsmasq-private.pid
      ExecReload=/bin/kill -HUP $MAINPID
      Restart = always

      [Install]
      WantedBy=multi-user.target

- name: Enable auto restart of dnsmasq
  systemd:
    name: dnsmasq-private
    enabled: yes
    state: stopped
